### ISSUE TITLE
can't install mljar mercury with python 3.9.11 , unicode error

### ISSUE THREAD

**Issue by doubianimehdi** [mljar/mercury#83]
Hi !

I'm trying to install mljar mercury on my new pc and I have the following error : 
Collecting mljar-mercury
  Using cached mljar-mercury-0.6.8.tar.gz (2.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\doub2420\AppData\Local\Temp\pip-build-env-1tu8thb3\overlay\Lib\site-packages\setuptools\build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "C:\Users\doub2420\AppData\Local\Temp\pip-build-env-1tu8thb3\overlay\Lib\site-packages\setuptools\build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "C:\Users\doub2420\AppData\Local\Temp\pip-build-env-1tu8thb3\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 5, in <module>
          long_description = fh.read()
        File "C:\Users\doub2420\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 3796: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

I have python 3.9.11
Same error using pip ...

Thank you !

**Comment by pplonski** [comment]
@doubianimehdi thanks for reporting. The issue is similar to https://stackoverflow.com/questions/71756399/pip-install-mljar-mercury-failing-with-codec-decode-issue

Will look into this and let you know.

**Comment by doubianimehdi** [comment]
installing mljar-mercury 0.5.1 seems to be working, installing 0.6.0 and above gives the same error

**Comment by doubianimehdi** [comment]
But even then , I'm having strange errors on zope.event and jinja2 ... it's not working ...

**Comment by doubianimehdi** [comment]
Traceback (most recent call last):
  File "C:\Users\doub2420\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\doub2420\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\Scripts\jupyter-nbconvert.EXE\__main__.py", line 7, in <module>
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\lib\site-packages\jupyter_core\application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
    app.start()
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\lib\site-packages\nbconvert\nbconvertapp.py", line 361, in start
    self.convert_notebooks()
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\lib\site-packages\nbconvert\nbconvertapp.py", line 533, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\lib\site-packages\nbconvert\nbconvertapp.py", line 498, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\lib\site-packages\nbconvert\nbconvertapp.py", line 427, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\lib\site-packages\nbconvert\exporters\exporter.py", line 186, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\lib\site-packages\nbconvert\exporters\exporter.py", line 204, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\lib\site-packages\nbconvert\exporters\html.py", line 145, in from_notebook_node
    return super().from_notebook_node(nb, resources, **kw)
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\lib\site-packages\nbconvert\exporters\templateexporter.py", line 392, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\lib\site-packages\jinja2\environment.py", line 1291, in render
    self.environment.handle_exception()
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\lib\site-packages\jinja2\environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\share\jupyter\nbconvert\templates\lab\index.html.j2", line 3, in top-level template code
    {% from 'jupyter_widgets.html.j2' import jupyter_widgets %}
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\share\jupyter\nbconvert\templates\lab\base.html.j2", line 234, in top-level template code
    {% set div_id = uuid4() %}
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\share\jupyter\nbconvert\templates\base\display_priority.j2", line 1, in top-level template code
    {%- extends 'base/null.j2' -%}
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\share\jupyter\nbconvert\templates\base\null.j2", line 24, in top-level template code
    {%- block header -%}
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\share\jupyter\nbconvert\templates\lab\index.html.j2", line 9, in block 'header'
    {%- block html_head -%}
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\share\jupyter\nbconvert\templates\lab\index.html.j2", line 36, in block 'html_head'
    {% block notebook_css %}
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\share\jupyter\nbconvert\templates\lab\index.html.j2", line 37, in block 'notebook_css'
    {{ resources.include_css("static/index.css") }}
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\lib\site-packages\nbconvert\exporters\html.py", line 151, in resources_include_css
    return jinja2.Markup(code)
AttributeError: module 'jinja2' has no attribute 'Markup'
Error during notebook initialization. NOT NULL constraint failed: notebooks_notebook.share


System check identified no issues (0 silenced).
April 14, 2022 - 09:44:48
Django version 3.2.5, using settings 'server.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Traceback (most recent call last):
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\Scripts\celery-script.py", line 33, in <module>
    sys.exit(load_entry_point('celery==5.1.2', 'console_scripts', 'celery')())
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\lib\site-packages\celery-5.1.2-py3.9.egg\celery\__main__.py", line 13, in main
    maybe_patch_concurrency()
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\lib\site-packages\celery-5.1.2-py3.9.egg\celery\__init__.py", line 141, in maybe_patch_concurrency
    patcher()
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\lib\site-packages\celery-5.1.2-py3.9.egg\celery\__init__.py", line 114, in _patch_gevent
    gevent.monkey.patch_all()
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\lib\site-packages\gevent-21.12.0-py3.9-win-amd64.egg\gevent\monkey.py", line 1253, in patch_all
    from gevent import events
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\lib\site-packages\gevent-21.12.0-py3.9-win-amd64.egg\gevent\events.py", line 71, in <module>
    from zope.event import subscribers
ModuleNotFoundError: No module named 'zope.event'

**Comment by pplonski** [comment]
@doubianimehdi thank you for checking!

I think I fixed the bug - there was an issue with an encoding when reading the `README.md` file. I've released the version `0.6.9`. Could you please try to update the package?

```
pip install mljar-mercury==0.6.9
```

The above issue with jinja2 shouldn't occur in the latest mljar-mercury version.

**Comment by doubianimehdi** [comment]
it's working ! But I still have this error : System check identified no issues (0 silenced).
April 14, 2022 - 09:53:34
Django version 3.2.5, using settings 'server.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Traceback (most recent call last):
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\Scripts\celery-script.py", line 33, in <module>
    sys.exit(load_entry_point('celery==5.1.2', 'console_scripts', 'celery')())
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\lib\site-packages\celery-5.1.2-py3.9.egg\celery\__main__.py", line 13, in main
    maybe_patch_concurrency()
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\lib\site-packages\celery-5.1.2-py3.9.egg\celery\__init__.py", line 141, in maybe_patch_concurrency
    patcher()
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\lib\site-packages\celery-5.1.2-py3.9.egg\celery\__init__.py", line 114, in _patch_gevent
    gevent.monkey.patch_all()
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\lib\site-packages\gevent-21.12.0-py3.9-win-amd64.egg\gevent\monkey.py", line 1253, in patch_all
    from gevent import events
  File "C:\Users\doub2420\.virtualenvs\wos_parser-3ahBjB9p\lib\site-packages\gevent-21.12.0-py3.9-win-amd64.egg\gevent\events.py", line 71, in <module>
    from zope.event import subscribers
ModuleNotFoundError: No module named 'zope.event'

**Comment by pplonski** [comment]
@doubianimehdi please try in the fresh terminal ... Just start mercury in the fresh console window. 

This might be some logs because the background task processor was too quickly shut down.

Please let me know if it works for you.

**Comment by doubianimehdi** [comment]
I did try in a fresh terminal , still the same message about zope.event ... BUT the rest seems to be working ! Thank you so much !!! I really need your package for a demo tomorrow !

**Comment by pplonski** [comment]
Please try:

```
pip3 install --force-reinstall zope.event
```
I found it here https://github.com/sham00n/buster/issues/20


May I ask what are you building? and how have you found Mercury? (I'm trying to reach more users)

**Comment by doubianimehdi** [comment]
It's not working ...
I'm building an NLP topic modeling for scientific papers exploration with BERT and i've found mercury from a post on linkedin :)

**Comment by pplonski** [comment]
@doubianimehdi do you still have `ModuleNotFoundError: No module named 'zope.event'` errors? Have you managed to build&deploy an app with Mercury?

**Comment by Konsilion** [comment]
Hello everyone,

I'm looking forward to using this tool. Only when I try to install it locally, I have a problem on the installation. 

My version of python is 3.10
Windows : 10

I hope my info is enough.

`Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\python310\lib\site-packages (from jsonschema>=2.6->nbformat>=5.1->nbconvert>=6.5.0->mljar-mercury==0.6.9) (0.18.1)
Using legacy 'setup.py install' for psutil, since package 'wheel' is not installed.
Installing collected packages: psutil, markdown, greenlet, click, asgiref, amqp, sqlalchemy, kombu, ipython, gevent, django, click-repl, click-plugins, click-didyoumean, ipykernel, djangorestframework, django-storages, django-filter, django-cors-headers, celery, django-drf-filepond, mljar-mercury
  Attempting uninstall: psutil
    Found existing installation: psutil 5.9.0
    Uninstalling psutil-5.9.0:
      Successfully uninstalled psutil-5.9.0
  Running setup.py install for psutil ... error
  error: subprocess-exited-with-error

  × Running setup.py install for psutil did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.10
      creating build\lib.win-amd64-3.10\psutil
      copying psutil\_common.py -> build\lib.win-amd64-3.10\psutil
      copying psutil\_compat.py -> build\lib.win-amd64-3.10\psutil
      copying psutil\_psaix.py -> build\lib.win-amd64-3.10\psutil
      copying psutil\_psbsd.py -> build\lib.win-amd64-3.10\psutil
      copying psutil\_pslinux.py -> build\lib.win-amd64-3.10\psutil
      copying psutil\_psosx.py -> build\lib.win-amd64-3.10\psutil
      copying psutil\_psposix.py -> build\lib.win-amd64-3.10\psutil
      copying psutil\_pssunos.py -> build\lib.win-amd64-3.10\psutil
      copying psutil\_pswindows.py -> build\lib.win-amd64-3.10\psutil
      copying psutil\__init__.py -> build\lib.win-amd64-3.10\psutil
      creating build\lib.win-amd64-3.10\psutil\tests
      copying psutil\tests\runner.py -> build\lib.win-amd64-3.10\psutil\tests
      copying psutil\tests\test_aix.py -> build\lib.win-amd64-3.10\psutil\tests
      copying psutil\tests\test_bsd.py -> build\lib.win-amd64-3.10\psutil\tests
      copying psutil\tests\test_connections.py -> build\lib.win-amd64-3.10\psutil\tests
      copying psutil\tests\test_contracts.py -> build\lib.win-amd64-3.10\psutil\tests
      copying psutil\tests\test_linux.py -> build\lib.win-amd64-3.10\psutil\tests
      copying psutil\tests\test_memleaks.py -> build\lib.win-amd64-3.10\psutil\tests
      copying psutil\tests\test_misc.py -> build\lib.win-amd64-3.10\psutil\tests
      copying psutil\tests\test_osx.py -> build\lib.win-amd64-3.10\psutil\tests
      copying psutil\tests\test_posix.py -> build\lib.win-amd64-3.10\psutil\tests
      copying psutil\tests\test_process.py -> build\lib.win-amd64-3.10\psutil\tests
      copying psutil\tests\test_sunos.py -> build\lib.win-amd64-3.10\psutil\tests
      copying psutil\tests\test_system.py -> build\lib.win-amd64-3.10\psutil\tests
      copying psutil\tests\test_testutils.py -> build\lib.win-amd64-3.10\psutil\tests
      copying psutil\tests\test_unicode.py -> build\lib.win-amd64-3.10\psutil\tests
      copying psutil\tests\test_windows.py -> build\lib.win-amd64-3.10\psutil\tests
      copying psutil\tests\__init__.py -> build\lib.win-amd64-3.10\psutil\tests
      copying psutil\tests\__main__.py -> build\lib.win-amd64-3.10\psutil\tests
      running build_ext
      building 'psutil._psutil_windows' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  WARNING: No metadata found in c:\python310\lib\site-packages
  Rolling back uninstall of psutil
  Moving to c:\python310\lib\site-packages\psutil-5.9.0.dist-info\
   from C:\Python310\Lib\site-packages\~sutil-5.9.0.dist-info
  Moving to c:\python310\lib\site-packages\psutil\
   from C:\Python310\Lib\site-packages\~sutil
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> psutil

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.`

**Comment by Konsilion** [comment]
Sorry ... i just follow : 

`Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
[end of output]`

The installation work ;)

**Comment by pplonski** [comment]
The issue is fixed. Closing.
